### ISSUE TITLE
groupadd command can not be found when running pack_image.sh

### ISSUE THREAD

**Issue by Tunglies** [D-Robotics/x5-rdk-gen#1]
```bash
$ git log -1
commit 19a018c7c732de7cfa72ee55a1c9d20f399ad480 (HEAD -> develop, origin/develop, origin/HEAD)
Author: xin03.liu <xin03.liu@horizon.cc>
Date:   Sun Sep 29 11:16:27 2024 +0800

    fix(samplefs): Add libgles2-mesa-dev ocl-icd-libopencl1 opencl-headers

    Signed-off-by: xin03.liu <xin03.liu@horizon.cc>
```

``` bash
$ sudo ./pack_image.sh
....
....
tar -xzf ~/x5-rdk-gen/rootfs/samplefs*.tar.gz -C ~/x5-rdk-gen/deploy/rootfs
Custom Special Modifications
Disabling NetworkManager-wait-online.service
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
/bin/bash: 行 1: groupadd: 未找到命令
新的密码： 重新输入新的密码： passwd：已成功更新密码
/bin/bash: 行 1: useradd: 未找到命令
```

 I found the relevant code takes effect.

https://github.com/D-Robotics/x5-rdk-gen/blob/19a018c7c732de7cfa72ee55a1c9d20f399ad480/hobot_customize_rootfs.sh#L93

The manual execution get the same result.

```bash
$ sudo chroot ~/x5-rdk-gen/deploy/rootfs /bin/bash -c "groupadd"
/bin/bash: 行 1: groupadd: 未找到命令
```

**Comment by YaQiang-Li** [comment]
Please execute the following commands to find the two missing programs:
ls -l rootfs

cd deploy/rootfs
find -iname groupadd
find -iname useradd

**Comment by Tunglies** [comment]
There are `useradd` and `groupadd`.
```bash
$ sudo find  -iname groupadd
./usr/sbin/groupadd
./usr/share/bash-completion/completions/groupadd

$ sudo find  -iname useradd
./usr/sbin/useradd
./usr/share/bash-completion/completions/useradd
./etc/default/useradd
```

And then works when chroot into it.
```bash
root@OpiPlus:/# /usr/sbin/groupadd
用法：groupadd [选项] 组

选项:
  -f, --force                   如果组已经存在则成功退出
                                并且如果 GID 已被使用则取消 -g
  -g, --gid GID                 为新组使用 GID
  -h, --help                    显示此帮助信息并退出
  -K, --key KEY=VALUE           不使用 /etc/login.defs 中的默认值
  -o, --non-unique              允许创建有重复 GID 的组
  -p, --password PASSWORD       为新组使用此加密过的密码
  -r, --system                  创建一个系统账户
  -R, --root CHROOT_DIR         chroot 到的目录
  -P, --prefix PREFIX_DIR       directory prefix
      --extrausers              Use the extra users database
```

**Comment by YaQiang-Li** [comment]
The default samplefs is in English, and yours is in Chinese. Did you customize samplefs?

`$ sudo chroot /home/hobot/2-x5-dev/rdk-gen/deploy/rootfs
root@ubuntu:/# 
root@ubuntu:/# ls
app  bin  boot  dev  etc  home  lib  media  mnt  opt  proc  root  run  sbin  srv  sys  tftpboot  tmp  userdata  usr  var
root@ubuntu:/# /usr/sbin/groupadd
Usage: groupadd [options] GROUP

Options:
  -f, --force                   exit successfully if the group already exists,
                                and cancel -g if the GID is already used
  -g, --gid GID                 use GID for the new group
  -h, --help                    display this help message and exit
  -K, --key KEY=VALUE           override /etc/login.defs defaults
  -o, --non-unique              allow to create groups with duplicate
                                (non-unique) GID
  -p, --password PASSWORD       use this encrypted password for the new group
  -r, --system                  create a system account
  -R, --root CHROOT_DIR         directory to chroot into
  -P, --prefix PREFIX_DIR       directory prefix
      --extrausers              Use the extra users database

root@ubuntu:/# `
